name: Mirror DockerHub

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'The name of Image to be Mirrored'
        type: choice
        options:
          - ''
          - 'buildkit'
          - 'maven'
          - 'eclipse-temurin'
          - 'golang'
          - 'node'
          - 'nginx'
          - 'plugin-docker-buildx'
          - 'plugin-sonarqube-scanner'
        default: ''
        
jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: buildkit
            repo: docker.io
            image: moby/buildkit
            multi-arch: system
          - name: maven
            image: maven
            repo: docker.io
            multi-arch: system
          - name: eclipse-temurin
            image: eclipse-temurin
            repo: docker.io
            multi-arch: all
          - name: golang
            image: golang
            repo: docker.io
            multi-arch: system
          - name: node
            image: node
            repo: docker.io
            multi-arch: all
          - name: nginx
            image: nginx
            repo: docker.io
            multi-arch: all
          - name: plugin-docker-buildx
            image: woodpecker-plugins/docker-buildx
            repo: codeberg.org
            dest-image: plugin-docker-buildx
            multi-arch: system
          - name: plugin-sonarqube-scanner
            repo: docker.io
            image: plugins/sonarqube-scanner
            dest-image: woodpecker-plugins/sonarqube-scanner
            multi-arch: system
          - name: plugin-dependency-check
            repo: docker.io
            image: owasp/dependency-check
            dest-image: woodpecker-plugins/dependency-check
            multi-arch: system
    steps:
      - uses: actions/checkout@v4
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Log in to My Gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GITEA_SERVER }}
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_ACCESS_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up skopeo environment         
        uses: balena-io-experimental/setup-skopeo-action@main
        # uses: warjiang/setup-skopeo@v0.1.3
        with:
          version: latest
          
      - name: 'Skopeo copy images to My Gitea'
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}
        run: |
          skopeo --version
          for tag in $(cat ./images/${{ matrix.name }}); do
            skopeo copy --multi-arch ${{ matrix.multi-arch || 'system' }}  \
              docker://${{ matrix.repo }}/${{ matrix.image }}:$tag \
              docker://${{ secrets.GITEA_SERVER }}/${{ secrets.GITEA_REPOSITORY }}/${{ matrix.dest-image || matrix.image }}:$tag
          done
          
