name: Mirror DockerHub

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: 'The name of Image to be Mirrored'
        type: choice
        options:
          - ''
          - 'buildkit'
          - 'eclipse-temurin'
          - 'golang'
          - 'maven'
          - 'nginx'
          - 'node'
          - 'plugin-dependency-check'
          - 'plugin-docker-buildx'
          - 'plugin-dockle'
          - 'plugin-extend-env'
          - 'plugin-kaniko'
          - 'plugin-node-pm'
          - 'plugin-sonarqube-scanner'
          - 'plugin-trivy'
        default: ''
        
jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: buildkit
            repo: docker.io
            image: moby/buildkit
            multi-arch: system
          - name: maven
            repo: docker.io
            image: maven
            multi-arch: system
          - name: eclipse-temurin
            repo: docker.io
            image: eclipse-temurin
            multi-arch: all
          - name: golang
            repo: docker.io
            image: golang
            multi-arch: system
          - name: node
            repo: docker.io
            image: node
            multi-arch: all
          - name: nginx
            repo: docker.io
            image: nginx
            multi-arch: all
          - name: plugin-docker-buildx
            repo: codeberg.org
            image: woodpecker-plugins/docker-buildx
            dest-image: woodpecker-plugins/plugin-docker-buildx
            multi-arch: system
          - name: plugin-dockle
            repo: docker.io
            image: euryecetelecom/woodpeckerci-dockle
            dest-image: woodpecker-plugins/plugin-dockle
            multi-arch: system
          - name: plugin-extend-env
            repo: docker.io
            image: woodpeckerci/plugin-extend-env
            dest-image: woodpecker-plugins/plugin-extend-env
            multi-arch: system
          - name: plugin-kaniko
            repo: docker.io
            image: woodpeckerci/plugin-kaniko
            dest-image: woodpecker-plugins/plugin-kaniko
            multi-arch: system
          - name: plugin-node-pm
            repo: codeberg.org
            image: woodpecker-plugins/node-pm
            dest-image: woodpecker-plugins/plugin-node-pm
            multi-arch: system
          - name: plugin-sonarqube-scanner
            repo: docker.io
            image: plugins/sonarqube-scanner
            dest-image: woodpecker-plugins/plugin-sonarqube-scanner
            multi-arch: system
          - name: plugin-dependency-check
            repo: docker.io
            image: owasp/dependency-check
            dest-image: woodpecker-plugins/plugin-dependency-check
            multi-arch: system
          - name: plugin-trivy
            repo: codeberg.org
            image: woodpecker-plugins/trivy
            dest-image: woodpecker-plugins/plugin-trivy
            multi-arch: system
    steps:
      - uses: actions/checkout@v4
          
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      
      - name: Log in to My Gitea
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.GITEA_SERVER }}
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_ACCESS_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Set up skopeo environment         
        uses: balena-io-experimental/setup-skopeo-action@main
        # uses: warjiang/setup-skopeo@v0.1.3
        with:
          version: latest
          
      - name: 'Skopeo copy images to My Gitea'
        if: ${{ github.event.inputs.IMAGE_NAME == '' || github.event.inputs.IMAGE_NAME == matrix.name }}
        run: |
          skopeo --version
          for tag in $(cat ./images/${{ matrix.name }}); do
            skopeo copy --multi-arch ${{ matrix.multi-arch || 'system' }}  \
              docker://${{ matrix.repo }}/${{ matrix.image }}:$tag \
              docker://${{ secrets.GITEA_SERVER }}/${{ secrets.GITEA_REPOSITORY }}/${{ matrix.dest-image || matrix.image }}:$tag
          done
          
